#WORK BY BETTYE J. TAYLOR 
# WORK IS MADE FOR ACTIVE RECALL AND LEARNING 
# MEANING OF PROJECT IS TO MAKE AN SIMPLE VARIABLE 
# WORK COMPLETE IN LESS THAN 15 MINUTES 



# AGE BASED PROJECT 

# NOW LETS ASK FOR THE AGE AND MAKE A INPUT VALUE 

name = input("What's your name?: ")
name_str =str(name) 


current_age = input("What is your age?: ")
current_age = int(current_age)
print("Your age is: ", current_age, "and your name is:", name)
